[book]
authors = ["Magnus Madsen"]
language = "en"
multilingual = false
src = "src"
title = "Advanced Programming"

[output.html]
git-repository-url = "https://github.com/magnus-madsen/advprog"
edit-url-template  = "https://github.com/magnus-madsen/advprog/edit/master/{path}"
